services:
  redis:
    image: redis:latest
    container_name: redis-lab2            # было redis
    ports:
      - "6379:6379"
    networks:
      - backend

  app1:
    build: .
    container_name: java-app1-lab2        # было java-app1
    environment:
      - REDIS_HOST=redis-lab2             # ссылка на новый сервис redis
      - REDIS_PORT=6379
      - PORT=8080
    ports:
      - "8081:8080"
    depends_on:
      - redis
    networks:
      - backend

  app2:
    build: .
    container_name: java-app2-lab2        # было java-app2
    environment:
      - REDIS_HOST=redis-lab2
      - REDIS_PORT=6379
      - PORT=8080
    ports:
      - "8082:8080"
    depends_on:
      - redis
    networks:
      - backend

  app3:
    build: .
    container_name: java-app3-lab2        # было java-app3
    environment:
      - REDIS_HOST=redis-lab2
      - REDIS_PORT=6379
      - PORT=8080
    ports:
      - "8083:8080"
    depends_on:
      - redis
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx-lb-lab2         # было nginx-lb
    ports:
      - "80:80"                           # если порт 80 занят, можно изменить на другой, например 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - backend

networks:
  backend:
    driver: bridge
    name: backend-lab2                     # лучше дать уникальное имя сети